### PR TITLE
[TODO TESTING] UserRoleModel Re-Constructed

### PR DESCRIPTION
**Pull request by mcanatalay**
Now, all users has role_id. This role id has its background info in roles. Roles only contain name of role and its id. Permissions does real job. It contains permission name and its granted value. For example if you want to give someone a admin permission. Just add Admin to permission name, and call it as,
getUserPermission($user_id,$permission_name);
OR
getRolePermission(Request::get('user_role'));

### CODE REVIEW

**Comment by mcanatalay** [comment]
Well, I guess it does not take much attention.

**Comment by panique** [comment]
Hey @mcanatalay , thanks a lot! This is just a very small private project and I currently don't have time to check the commits properly, but I'll definitly do sometime on the weekend.

To be honest: There's currently summer here in Berlin and I'm just to lazy to do this too :)

Please give this this some time, over the weeks every commits gets a proper review and as this is a security-critical projects every line needs special treatment and very accurate testing.

Have a sunny day

**Comment by panique** [comment]
Hey, this looks really good, buuut I think it's too complex for the minimal-use-case approach of the project (plus there are some merge conflicts, but that's a problem on my side). As I'm planning to put HUGE to End of Life, meaning no new feature anymore, I would kindly close this pull requests, but link it from the readme, so everybody who want the role/permission feature can easily find your code and merge it if needed.

Thanks for the commits, I hope that's okay for you! :)

**Comment by p1Ggy** [comment]
@mcanatalay Hey man, I like these changes.
May I ask are these changes still valid they not going to break anything, because I would like to add this to my project.

**Pull request closed without merging**
