### PR TITLE
Functionality to delete a user's avatar

### PR DESCRIPTION
**Pull request by Dominic28**
Hey,
I needed this for a project. Feel free to merge this :) You just have to place a link somwhere in your design.

Personally, I renamed the uploadAvatar area to editAvatar and moved it in a user-controller which looks like this:

unbenannt

### CODE REVIEW

**Comment by Dominic28** [comment]
I changed AvatarModel to self^^
I think panique wanted to put something into a new UserController. This is why i justed placed it next to the uploadAvatar function.

**Comment by oisian1** [comment]
Ah, i must of missed that conversation, it really doesn't make a whole heap of sense where it currently is does it. as to this feature, I think that this should be implemented, as it extends on functionality that is  already there, if you can add something you should be able to remove it. that's how i see it

**Comment by Dominic28** [comment]
I don't have a link to the issue right now, but it was at the time where @panique splitted the login model.
The UserModel is already existing and he wanted to move the user stuff from the login controller to a user controller.

**Comment by oisian1** [comment]
Side note, You should probably add a way for the user to use this feature, i cant imagine it will get merged without it

**Comment by panique** [comment]
Thanks, excellent! I'll make a test tomorrow and then merge it!
Personal notice: Maybe this should also check for .png etc. too

**Comment by panique** [comment]
@Dominic28 Can you please add something that makes this feature useable for the user ? currently it's more or less unreachable code :)

**Comment by Dominic28** [comment]
I added the link to the upload avatar page and renamed it to edit avatar. I hope this is okay for you.

**Comment by panique** [comment]
BIG Thanks, works perfectly! :)

**Pull request merged**
