### PR TITLE
Issue #770

### PR DESCRIPTION
**Pull request by abmmhasan**
This is the solution discussed in #770

### CODE REVIEW

**Comment by slaveek** [comment]
This solution have small issue look here -> https://github.com/panique/huge/issues/770#issuecomment-168518690

**Comment by abmmhasan** [comment]
Well, I just changed according to your updated solution!

**Comment by panique** [comment]
Thanks, I've just merged this manually via patch file as github cannot merge this automatically (merge conflicts)

**Comment by panique** [comment]
Cool feature btw! Nice, thanks! :)

**Comment by slaveek** [comment]
Hi I'm afraid that you didn't put all changes ;) in LoginController.
After your changes looks:
```php
// check login status: if true, then redirect user to user/index, if false, then to login form again
if ($login_successful) {
    if (Request::post('redirect')) {
        Redirect::toPreviousViewedPageAfterLogin(ltrim(urldecode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('user/index');
    }
} else {
    Redirect::to('login/index');
}
```
but to work this flawless we need to add more action when login is failed:
```php
// check login status: if true, then redirect user to user/index, if false, then to login form again
if ($login_successful) {
    if (Request::post('redirect')) {
        Redirect::toPreviousViewedPageAfterLogin(ltrim(urldecode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('user/index');
    }
} else {
    if (Request::post('redirect')) {
        Redirect::to('login?redirect=' . ltrim(urlencode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('login/index');
    }
}
```
Here is a bit more https://github.com/panique/huge/issues/770#issuecomment-168518690

**Comment by panique** [comment]
OH damn it :) I've just fixed this and it's now in develop branch! Thanks for the good eye for the details!

**Comment by slaveek** [comment]
I can create pull request with that fix if you don't mind.

**Comment by panique** [comment]
No prob it's already in dev branch!

**Pull request closed without merging**
